# Generated by Django 4.2.1 on 2023-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.FileField(upload_to='./files/')),
                ('sourceType', models.CharField(max_length=200)),
                ('sourceFile', models.FileField(upload_to='./files/')),
            ],
        ),
        migrations.CreateModel(
            name='UserSoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('soundID', models.IntegerField()),
            ],
        ),
    ]
